### ISSUE TITLE
** (ArgumentError) argument error on executing code in `pry` session with tests

### ISSUE THREAD

**Issue by kanmaniselvan** [sasa1977/boundary#14]
**Environment**:

Elixir 1.10.1
MacOS 10.15.3 (19D76)

**Issue**:

I get the following error from `boundary` on every command that I run in the `pry` session during tests.

I run the test with,
```elixir
$ iex -S mix test --trace test_file.exs:30
```  
and on the `pry` session,

```elixir
  107:   
  108:   defp perform_step(data) do
  109:     require IEx; IEx.pry
  110:   
Allow? [Yn] 
Interactive Elixir (1.10.1) - press Ctrl+C to exit (type h() ENTER for help)
```

This the error that I get on executing any valid command, 

```elixir
pry(1)> data |> Map.keys()
** (ArgumentError) argument error
    (stdlib 3.11.2) :ets.insert_new(:boundary_xref_seen_modules, {SomeModule})
    (boundary 0.2.0) lib/boundary/xref.ex:18: Boundary.Xref.add_call/2
    (boundary 0.2.0) lib/mix/tasks/compile/boundary.ex:102: Mix.Tasks.Compile.Boundary.trace/2
    (elixir 1.10.1) src/elixir_env.erl:36: :elixir_env."-trace/2-lc$^0/1-0-"/3
    (elixir 1.10.1) src/elixir_env.erl:36: :elixir_env.trace/2
    (elixir 1.10.1) expanding macro: Kernel.|>/2
    (some_application 4.41.0-15-gf336d260) lib/xxxxxx.ex:1: SomeModule.perform_step/1
```

but the pattern matching works,

```elixir
pry(2)> %{} = data
```

I also did some random error cases,

**case 1:**
```elixir
pry(3)> a   
** (UndefinedFunctionError) function :erl_eval.a/0 is undefined or private
    (stdlib 3.11.2) :erl_eval.a/0
    (stdlib 3.11.2) erl_eval.erl:583: :erl_eval.local_func/6
    (iex 1.10.1) lib/iex/evaluator.ex:258: IEx.Evaluator.handle_eval/5
    (iex 1.10.1) lib/iex/evaluator.ex:239: IEx.Evaluator.do_eval/3
    (iex 1.10.1) lib/iex/evaluator.ex:217: IEx.Evaluator.eval/3
    (iex 1.10.1) lib/iex/evaluator.ex:103: IEx.Evaluator.loop/1
    (iex 1.10.1) lib/iex/evaluator.ex:27: IEx.Evaluator.init/4
```

**case 2:**
```elixir
pry(3)> a + a
** (ArgumentError) argument error
    (stdlib 3.11.2) :ets.insert_new(:boundary_xref_seen_modules, {SomeModule})
    (boundary 0.2.0) lib/boundary/xref.ex:18: Boundary.Xref.add_call/2
    (boundary 0.2.0) lib/mix/tasks/compile/boundary.ex:102: Mix.Tasks.Compile.Boundary.trace/2
    (elixir 1.10.1) src/elixir_env.erl:36: :elixir_env."-trace/2-lc$^0/1-0-"/3
    (elixir 1.10.1) src/elixir_env.erl:36: :elixir_env.trace/2
    (iex 1.10.1) lib/iex/evaluator.ex:258: IEx.Evaluator.handle_eval/5
    (iex 1.10.1) lib/iex/evaluator.ex:239: IEx.Evaluator.do_eval/3
    (iex 1.10.1) lib/iex/evaluator.ex:217: IEx.Evaluator.eval/3
    (iex 1.10.1) lib/iex/evaluator.ex:103: IEx.Evaluator.loop/1
    (iex 1.10.1) lib/iex/evaluator.ex:27: IEx.Evaluator.init/4
```

**Comment by sasa1977** [comment]
I tried reproducing this locally but I couldn't. I also changed some code and tried recompiling, but even that worked. Could you setup some minimal repo somewhere so I can give that a try?

**Comment by kanmaniselvan** [comment]
I tried with new repo, but I also was not to reproduce the issue. But it was happening in my current work repo, which is quite big. 

The issues automatically fixed after I removed `erlang` entirely, reinstalled and rebuilt along with the deps. 

Thanks for the support @sasa1977
