### ISSUE TITLE
Error while running `mix boundary.visualize Boundary` 

### ISSUE THREAD

**Issue by Skoda091** [sasa1977/boundary#50]
## Environment

- Elixir 1.13.0 (compiled with Erlang/OTP 24)
- Operating system: macOS 12.3.1

## Situation

Running `mix boundary.visualize.mods Boundary` fails with:

```elixir
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: the table identifier does not refer to an existing ETS table

    (stdlib 3.16.1) :ets.match_object(Boundary.Mix.Xref.Entries, :_)
    (stdlib 3.16.1) ets.erl:764: :ets.tab2list/1
    (boundary 0.9.2) lib/boundary/mix/xref.ex:59: Boundary.Mix.Xref.entries/0
    (boundary 0.9.2) lib/boundary/mix/tasks/visualize/mods.ex:34: Mix.Tasks.Boundary.Visualize.Mods.run/1
    (mix 1.13.0) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.13.0) lib/mix/cli.ex:84: Mix.CLI.run_task/2
    (elixir 1.13.0) lib/code.ex:1183: Code.require_file/2
```

## Expected behavior

Generates graph in .dot language.

**Comment by Nezteb** [comment]
@Skoda091 Do you have a reliable way to reproduce this? A sample project or something similar?
